name: Deploy Spotify Crawler Lambda Function

on:
    push:
      branches:
        - main
      paths:
        - 'src/cloud/lambdas/recently_played/**'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 'Checkout repo'
              uses: actions/checkout@v4

            - name: 'Setup AWS Credentials'
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
                aws-region: 'sa-east-1'
            
            - name: 'Update Lambda: recently_played'
              run: |
                cd src/cloud/lambdas/recently_played/
                zip -r recently_played.zip .
                aws lambda update-function-code --function-name recently_played_songs --zip-file fileb://recently_played.zip
                aws lambda update-function-configuration --function-name recently_played_songs --environment "Variables={CLIENT_SECRET=${{ secrets.CLIENT_SECRET }},CLIENT_ID=${{ secrets.CLIENT_ID }},REDIRECT_URI=${{ secrets.REDIRECT_URI }}}"

