name: Deploy ETL Lambda Functions

on:
    push:
      branches:
        - main
        - ci/cd # for testing.

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 'Checkout repo'
              uses: actions/checkout@v4

            - name: 'Setup AWS Credentials'
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
                aws-region: 'sa-east-1'
            
            - name: 'Deploy Lambda test1'
              run: |
                'echo hello world'
                'pwd'